theme = "discord"

[actions.buffer]
click_channel_name = "replace-pane"
click_highlight = "replace-pane"
click_username = "replace-pane"
local = "replace-pane"
message_channel = "replace-pane"
message_user = "replace-pane"

[actions.sidebar]
buffer = "replace-pane"

[buffer.channel.nicklist]
enabled = false

[buffer.channel.topic]
enabled = true
max_lines = 5

[buffer.server_messages.change_host]
enabled = false

[buffer.server_messages.change_mode]
enabled = false

[buffer.server_messages.change_nick]
enabled = false

[buffer.server_messages.change_topic]
enabled = false

[buffer.server_messages.join]
enabled = false

[buffer.server_messages.part]
enabled = false

[buffer.server_messages.quit]
enabled = false

[buffer.server_messages.topic]
enabled = false

[logs]
file_level = 'off'
pane_level = 'off'

[pane]
restore_on_launch = false

[servers.znc]
nickname = "user@identifier/network"
server = "irc.example.com"
password = "hunter2"
who_poll_enabled = false
